language: node_js
node_js:
  - "8"

script:
  - npm run build

deploy:
  - provider: pages
    skip-cleanup: true
    keep-history: true
    target-branch: npm
    github-token: $GITHUB_TRAVIS_CI_TOKEN
    local-dir: dist
    on:
      tags: true

  - provider: npm
    skip_cleanup: true
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
    on:
      tags: true